mysql-server:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_DATABASE: db
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: password
